version: '3'

services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_USERNAME=postgres
      - DB_PASSWORD=password123
      - DB_HOST=host.docker.internal
      - PRIVATE_KEY=74395e80-f851-4291-9d79-e21e3de37be6
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis/redis-stack-server:latest
    container_name: my-redis-container
    networks:
      - my-network
    ports:
      - "6380:6379"
    volumes:
      - .\config\redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  my-network:
    driver: bridge